eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

jwt:
  SECRET_KEY: e34bc93bce34083f4dc6900e986019e7f08cf994c01046348dd69f8f05f00cb9
  TOKEN_DURATION: 21600000  #6 saat

spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bilyoner_account_service_db
    username: postgres
    password: 123qweqwe
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
#  zipkin:
#    base-url: http://localhost:9411
#
#application:
#  config:
#    accounts-url: http://localhost:8222/accounts
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0