eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: coupons
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bilyoner_coupon_service_db
    username: postgres
    password: 123qweqwe
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
#  zipkin:
#    base-url: http://localhost:9411

#application:
#  config:
#    coupons-url: http://localhost:8222/coupons

#management:
#  tracing:
#    sampling:
#      probability: 1.0


