eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: coupons
          uri: http://localhost:8090
          predicates:
            - Path=/coupons/**
        - id: accounts
          uri: http://localhost:8070
          predicates:
            - Path=/account/**
  zipkin:
    base-url: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1.0

